name: "Test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Test building latest pyright version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
      - name: Install dev dependencies
        run: poetry install

      - name: Build the latest Pyright version
        run: poetry run python scripts/build_pyright.py latest

      - name: Build the wheel
        run: poetry build --format wheel
      
      - name: Print latest built wheel
        run: ls -AU dist/ | head -1

      - name: Install the wheel and test it 
        run: |
          mkdir test_wheel \
          && poetry init --quiet --name test_wheel --directory test_wheel/ \
          && poetry add --editable ../dist/$(ls -AU dist/ | head -1) --directory test_wheel/ \
          && poetry run --directory test_wheel/ pyright -- pyright_alright/main.py --verbose 

